/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fast_Food;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *Name And matric no Of the group member:
 * @author Md. Afique Amin Zian(1631005)
 * @author mehran mujib(1632625)
 * @author Nasik Sami Khan(1638153)
 * @author Abu Sayed Mohammed Saad(1634677)
 */

//all the variable and ther value
public class FastFood extends javax.swing.JFrame {
double price_bottlewater=1.9;
double price_cheesesandwich=2.2;
double price_chickensalad=2.5;
double price_chickensandwich=4.00;
double price_chocolatemilkshake=2.00;
double price_chocolatemuffin=3.00;
double price_coffee=1.2;                        
double price_cola=1.5;
double price_fishsandwich=3.00;
double price_fries=3.00;
double price_hamburger=2.7;
double price_hashbrown=2.6;
double price_onionrings=2.00;
double price_orange=1.5;
double price_pancakesyrup=1.4;
double price_pineapplestick= 1.7;
double price_salad=1.00;
double price_strawberryshake=3.00;
double price_tea=1.2;
double price_toastedbagel=3.00;
double price_vanilacone=3.8;
double price_vanilashake=4.00;
double taxrate=3.7;

double iTax,iTotal,iSubTotal,iChange,iCost;
double [] itemcost=new double[22];// declare aray

       
    /**
     * Creates new form FastFood
     */
    public FastFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbluppername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jchkonionrings = new javax.swing.JCheckBox();
        jchkfries = new javax.swing.JCheckBox();
        jchkhamburger = new javax.swing.JCheckBox();
        jchkchickensalad = new javax.swing.JCheckBox();
        jchksalad = new javax.swing.JCheckBox();
        jchkcheesesandwich = new javax.swing.JCheckBox();
        jchkchickensandwich = new javax.swing.JCheckBox();
        jchkfishsandwich = new javax.swing.JCheckBox();
        jlbfastfoodandvegetarian = new javax.swing.JLabel();
        jlblsandwich = new javax.swing.JLabel();
        jtxthamburger = new javax.swing.JTextField();
        jtxtonionrings = new javax.swing.JTextField();
        jtxtchickensalad = new javax.swing.JTextField();
        jtxtfries = new javax.swing.JTextField();
        jtxtsalad = new javax.swing.JTextField();
        jtxtcheesesandwich = new javax.swing.JTextField();
        jtxtchickensandwich = new javax.swing.JTextField();
        jtxtfishsandwich = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jchkpancakessyrup = new javax.swing.JCheckBox();
        jchkchocolatemuffin = new javax.swing.JCheckBox();
        jchkpineapplestick = new javax.swing.JCheckBox();
        jchktoastedbagel = new javax.swing.JCheckBox();
        jchkhashbrown = new javax.swing.JCheckBox();
        jlbldesserts = new javax.swing.JLabel();
        jtxthashbrown = new javax.swing.JTextField();
        jtxttoastedbagel = new javax.swing.JTextField();
        jtxtpineapplestick = new javax.swing.JTextField();
        jtxtchocolatemuffin = new javax.swing.JTextField();
        jtxtpancakessyrup = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jcombopaymentmethod = new javax.swing.JComboBox<>();
        jlblpaymentmethod = new javax.swing.JLabel();
        jtxtpaymentmethod = new javax.swing.JTextField();
        jbuttontotal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlbltax = new javax.swing.JLabel();
        jlblchange = new javax.swing.JLabel();
        jlblsubtotal = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jbuttonreset = new javax.swing.JButton();
        jbuttonexit = new javax.swing.JButton();
        jtxtsubtotal = new javax.swing.JTextField();
        jtxttotal = new javax.swing.JTextField();
        jtxttax = new javax.swing.JTextField();
        jtxtchange = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jchktea = new javax.swing.JCheckBox();
        jchkcola = new javax.swing.JCheckBox();
        jchkcoffee = new javax.swing.JCheckBox();
        jchkorange = new javax.swing.JCheckBox();
        jchkbottlewater = new javax.swing.JCheckBox();
        jchkvanilashake = new javax.swing.JCheckBox();
        jchkstrawberryshake = new javax.swing.JCheckBox();
        jchkchocolatemilkshake = new javax.swing.JCheckBox();
        jlbldrinks = new javax.swing.JLabel();
        jlblshakes = new javax.swing.JLabel();
        jchkvanilacone = new javax.swing.JCheckBox();
        jtxttea = new javax.swing.JTextField();
        jtxtcola = new javax.swing.JTextField();
        jtxtcoffee = new javax.swing.JTextField();
        jtxtorange = new javax.swing.JTextField();
        jtxtbottlewater = new javax.swing.JTextField();
        jtxtchocolatemilkshake = new javax.swing.JTextField();
        jtxtstrawberryshake = new javax.swing.JTextField();
        jtxtvanilashake = new javax.swing.JTextField();
        jtxtvanilacone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 900));
        setPreferredSize(new java.awt.Dimension(2500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jlbluppername.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jlbluppername.setText("                 Fast Food  Restaurant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbluppername, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbluppername, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1110, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jchkonionrings.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkonionrings.setText("Onion Rings");
        jchkonionrings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkonionringsActionPerformed(evt);
            }
        });

        jchkfries.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkfries.setText("Fries");
        jchkfries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkfriesActionPerformed(evt);
            }
        });

        jchkhamburger.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkhamburger.setText("Hamburger");
        jchkhamburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkhamburgerActionPerformed(evt);
            }
        });

        jchkchickensalad.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkchickensalad.setText("Chicken Salad");
        jchkchickensalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkchickensaladActionPerformed(evt);
            }
        });

        jchksalad.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchksalad.setText("Salad");
        jchksalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchksaladActionPerformed(evt);
            }
        });

        jchkcheesesandwich.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jchkcheesesandwich.setText("Cheese Sadnwich");
        jchkcheesesandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcheesesandwichActionPerformed(evt);
            }
        });

        jchkchickensandwich.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jchkchickensandwich.setText("Chicken Sandwich");
        jchkchickensandwich.setToolTipText("");
        jchkchickensandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkchickensandwichActionPerformed(evt);
            }
        });

        jchkfishsandwich.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkfishsandwich.setText("Fish Sandwich");
        jchkfishsandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkfishsandwichActionPerformed(evt);
            }
        });

        jlbfastfoodandvegetarian.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbfastfoodandvegetarian.setText("Fast Meal And Vegetarian");

        jlblsandwich.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblsandwich.setText("Sandwich");

        jtxthamburger.setEditable(false);
        jtxthamburger.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxthamburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxthamburger.setText("0");
        jtxthamburger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxthamburgerKeyTyped(evt);
            }
        });

        jtxtonionrings.setEditable(false);
        jtxtonionrings.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtonionrings.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtonionrings.setText("0");
        jtxtonionrings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtonionringsKeyTyped(evt);
            }
        });

        jtxtchickensalad.setEditable(false);
        jtxtchickensalad.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtchickensalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchickensalad.setText("0");
        jtxtchickensalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchickensaladKeyTyped(evt);
            }
        });

        jtxtfries.setEditable(false);
        jtxtfries.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtfries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfries.setText("0");
        jtxtfries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfriesActionPerformed(evt);
            }
        });
        jtxtfries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfriesKeyTyped(evt);
            }
        });

        jtxtsalad.setEditable(false);
        jtxtsalad.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtsalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsalad.setText("0");
        jtxtsalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtsaladKeyTyped(evt);
            }
        });

        jtxtcheesesandwich.setEditable(false);
        jtxtcheesesandwich.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtcheesesandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcheesesandwich.setText("0");
        jtxtcheesesandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcheesesandwichKeyTyped(evt);
            }
        });

        jtxtchickensandwich.setEditable(false);
        jtxtchickensandwich.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtchickensandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchickensandwich.setText("0");
        jtxtchickensandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchickensandwichKeyTyped(evt);
            }
        });

        jtxtfishsandwich.setEditable(false);
        jtxtfishsandwich.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtfishsandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfishsandwich.setText("0");
        jtxtfishsandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfishsandwichKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkchickensandwich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtchickensandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkcheesesandwich)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtcheesesandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbfastfoodandvegetarian)
                    .addComponent(jlblsandwich)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkfries, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchksalad)
                            .addComponent(jchkhamburger)
                            .addComponent(jchkonionrings))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtonionrings, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxthamburger, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtsalad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtfries, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkchickensalad)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtchickensalad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkfishsandwich)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtfishsandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbfastfoodandvegetarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkfries)
                    .addComponent(jtxtfries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchksalad)
                    .addComponent(jtxtsalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkhamburger)
                        .addGap(26, 26, 26)
                        .addComponent(jchkonionrings))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxthamburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtonionrings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkchickensalad)
                    .addComponent(jtxtchickensalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblsandwich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchkfishsandwich)
                    .addComponent(jtxtfishsandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkcheesesandwich)
                    .addComponent(jtxtcheesesandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkchickensandwich)
                    .addComponent(jtxtchickensandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 520));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jchkpancakessyrup.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkpancakessyrup.setText("Pancakes Syrup");
        jchkpancakessyrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkpancakessyrupActionPerformed(evt);
            }
        });

        jchkchocolatemuffin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkchocolatemuffin.setText("Chocolate Muffin");
        jchkchocolatemuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkchocolatemuffinActionPerformed(evt);
            }
        });

        jchkpineapplestick.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkpineapplestick.setText("Pineapple Stick");
        jchkpineapplestick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkpineapplestickActionPerformed(evt);
            }
        });

        jchktoastedbagel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchktoastedbagel.setText("Toasted Bagel");
        jchktoastedbagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchktoastedbagelActionPerformed(evt);
            }
        });

        jchkhashbrown.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkhashbrown.setText("Hash Brown");
        jchkhashbrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkhashbrownActionPerformed(evt);
            }
        });

        jlbldesserts.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbldesserts.setText("Desserts");

        jtxthashbrown.setEditable(false);
        jtxthashbrown.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxthashbrown.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxthashbrown.setText("0");
        jtxthashbrown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxthashbrownKeyTyped(evt);
            }
        });

        jtxttoastedbagel.setEditable(false);
        jtxttoastedbagel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxttoastedbagel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttoastedbagel.setText("0");
        jtxttoastedbagel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxttoastedbagelKeyTyped(evt);
            }
        });

        jtxtpineapplestick.setEditable(false);
        jtxtpineapplestick.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtpineapplestick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpineapplestick.setText("0");
        jtxtpineapplestick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpineapplestickKeyTyped(evt);
            }
        });

        jtxtchocolatemuffin.setEditable(false);
        jtxtchocolatemuffin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtchocolatemuffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchocolatemuffin.setText("0");
        jtxtchocolatemuffin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchocolatemuffinKeyTyped(evt);
            }
        });

        jtxtpancakessyrup.setEditable(false);
        jtxtpancakessyrup.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtpancakessyrup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpancakessyrup.setText("0");
        jtxtpancakessyrup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpancakessyrupKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlbldesserts)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkpancakessyrup)
                                    .addComponent(jchkchocolatemuffin)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchktoastedbagel)
                                    .addComponent(jchkhashbrown)
                                    .addComponent(jchkpineapplestick))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxthashbrown, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxttoastedbagel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtpineapplestick, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtchocolatemuffin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtpancakessyrup, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbldesserts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkhashbrown)
                    .addComponent(jtxthashbrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchktoastedbagel)
                    .addComponent(jtxttoastedbagel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtpineapplestick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkpineapplestick))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkchocolatemuffin)
                    .addComponent(jtxtchocolatemuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkpancakessyrup)
                    .addComponent(jtxtpancakessyrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 390, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jcombopaymentmethod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jcombopaymentmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit card", "Master Card", "Visa Card" }));
        jcombopaymentmethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombopaymentmethodActionPerformed(evt);
            }
        });

        jlblpaymentmethod.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlblpaymentmethod.setText("Payment Method");

        jtxtpaymentmethod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtpaymentmethod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpaymentmethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpaymentmethodActionPerformed(evt);
            }
        });
        jtxtpaymentmethod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpaymentmethodKeyTyped(evt);
            }
        });

        jbuttontotal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbuttontotal.setText("Total");
        jbuttontotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttontotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtpaymentmethod)
                        .addContainerGap())
                    .addComponent(jcombopaymentmethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblpaymentmethod)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbuttontotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlblpaymentmethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcombopaymentmethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtpaymentmethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttontotal)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 160, 220));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jlbltax.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlbltax.setText("Tax");

        jlblchange.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlblchange.setText("Change");

        jlblsubtotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlblsubtotal.setText("Sub Total");

        jlbltotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jlbltotal.setText("Total");

        jbuttonreset.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbuttonreset.setText("Reset");
        jbuttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonresetActionPerformed(evt);
            }
        });

        jbuttonexit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbuttonexit.setText("Exit");
        jbuttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonexitActionPerformed(evt);
            }
        });

        jtxtsubtotal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jtxtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsubtotalActionPerformed(evt);
            }
        });

        jtxttotal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jtxttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttotalActionPerformed(evt);
            }
        });

        jtxttax.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jtxttax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttaxActionPerformed(evt);
            }
        });

        jtxtchange.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jtxtchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtchangeActionPerformed(evt);
            }
        });
        jtxtchange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchangeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblchange)
                            .addComponent(jlbltax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxttax, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jtxtchange))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblsubtotal)
                            .addComponent(jlbltotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbuttonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jbuttonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblchange)
                    .addComponent(jtxtchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltax)
                    .addComponent(jtxttax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblsubtotal)
                    .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltotal)
                    .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonreset)
                    .addComponent(jbuttonexit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 230, 230));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jchktea.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchktea.setText("Tea");
        jchktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkteaActionPerformed(evt);
            }
        });

        jchkcola.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkcola.setText("Cola");
        jchkcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcolaActionPerformed(evt);
            }
        });

        jchkcoffee.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkcoffee.setText("Coffee");
        jchkcoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcoffeeActionPerformed(evt);
            }
        });

        jchkorange.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkorange.setText("Orange");
        jchkorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkorangeActionPerformed(evt);
            }
        });

        jchkbottlewater.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jchkbottlewater.setText("Bottle Water");
        jchkbottlewater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbottlewaterActionPerformed(evt);
            }
        });

        jchkvanilashake.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkvanilashake.setText("Vanila Shake");
        jchkvanilashake.setToolTipText("");
        jchkvanilashake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkvanilashakeActionPerformed(evt);
            }
        });

        jchkstrawberryshake.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkstrawberryshake.setText("Strawberry Shake");
        jchkstrawberryshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkstrawberryshakeActionPerformed(evt);
            }
        });

        jchkchocolatemilkshake.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jchkchocolatemilkshake.setText("Chocolate Milk Shake");
        jchkchocolatemilkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkchocolatemilkshakeActionPerformed(evt);
            }
        });

        jlbldrinks.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbldrinks.setText("Drinks");
        jlbldrinks.setToolTipText("");

        jlblshakes.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblshakes.setText("Shakes");

        jchkvanilacone.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jchkvanilacone.setText("Vanila Cone");
        jchkvanilacone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkvanilaconeActionPerformed(evt);
            }
        });

        jtxttea.setEditable(false);
        jtxttea.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxttea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttea.setText("0");
        jtxttea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtteaKeyTyped(evt);
            }
        });

        jtxtcola.setEditable(false);
        jtxtcola.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtcola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcola.setText("0");
        jtxtcola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcolaKeyTyped(evt);
            }
        });

        jtxtcoffee.setEditable(false);
        jtxtcoffee.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtcoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcoffee.setText("0");
        jtxtcoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcoffeeActionPerformed(evt);
            }
        });
        jtxtcoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcoffeeKeyTyped(evt);
            }
        });

        jtxtorange.setEditable(false);
        jtxtorange.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtorange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtorange.setText("0");
        jtxtorange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtorangeKeyTyped(evt);
            }
        });

        jtxtbottlewater.setEditable(false);
        jtxtbottlewater.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtbottlewater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtbottlewater.setText("0");
        jtxtbottlewater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtbottlewaterKeyTyped(evt);
            }
        });

        jtxtchocolatemilkshake.setEditable(false);
        jtxtchocolatemilkshake.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtchocolatemilkshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchocolatemilkshake.setText("0");
        jtxtchocolatemilkshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchocolatemilkshakeKeyTyped(evt);
            }
        });

        jtxtstrawberryshake.setEditable(false);
        jtxtstrawberryshake.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtstrawberryshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtstrawberryshake.setText("0");
        jtxtstrawberryshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtstrawberryshakeKeyTyped(evt);
            }
        });

        jtxtvanilashake.setEditable(false);
        jtxtvanilashake.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtvanilashake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtvanilashake.setText("0");
        jtxtvanilashake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtvanilashakeKeyTyped(evt);
            }
        });

        jtxtvanilacone.setEditable(false);
        jtxtvanilacone.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtxtvanilacone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtvanilacone.setText("0");
        jtxtvanilacone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtvanilaconeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblshakes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbldrinks, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchktea)
                                    .addComponent(jchkcoffee)
                                    .addComponent(jchkcola))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtcoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtcola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxttea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jchkorange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtorange, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jchkbottlewater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtbottlewater, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jchkvanilacone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtvanilacone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jchkvanilashake)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtvanilashake, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkstrawberryshake)
                                    .addComponent(jchkchocolatemilkshake))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtstrawberryshake, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtchocolatemilkshake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 53, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlbldrinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchktea)
                    .addComponent(jtxttea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jchkcola)
                        .addGap(31, 31, 31)
                        .addComponent(jchkcoffee)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchkorange)
                            .addComponent(jtxtorange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtcola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkbottlewater)
                    .addComponent(jtxtbottlewater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblshakes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkvanilacone)
                    .addComponent(jtxtvanilacone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkvanilashake)
                    .addComponent(jtxtvanilashake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkstrawberryshake)
                    .addComponent(jtxtstrawberryshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkchocolatemilkshake)
                    .addComponent(jtxtchocolatemilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 410, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //chicken sandwich checkbox
    private void jchkchickensandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkchickensandwichActionPerformed
if(jchkchickensandwich.isSelected())
        {
            jtxtchickensandwich.setEditable(true);
            jtxtchickensandwich.requestFocus();
            jtxtchickensandwich.setText("");
        }
        else{
        jtxtchickensandwich.setEditable(false);
        jtxtchickensandwich.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jchkchickensandwichActionPerformed
//hash brown checkbox
    private void jchkhashbrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkhashbrownActionPerformed
if(jchkhashbrown.isSelected())
        {
            jtxthashbrown.setEditable(true);
            jtxthashbrown.requestFocus();
            jtxthashbrown.setText("");
        }
        else{
        jtxthashbrown.setEditable(false);
        jtxthashbrown.setText("0");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jchkhashbrownActionPerformed
//subtoal text field
    private void jtxtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsubtotalActionPerformed

    private void jtxttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttotalActionPerformed

    private void jtxttaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttaxActionPerformed
//exit button code 
    private JFrame frame;
    private void jbuttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonexitActionPerformed
      frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit.","Fast Food", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            
        System.exit(0);
        }
    }//GEN-LAST:event_jbuttonexitActionPerformed
//Reset Button Action
    
    private void jbuttonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonresetActionPerformed
       
        jtxtfries.setText("0");
        jtxtsalad.setText("0");
        jtxthamburger.setText("0");
        jtxtonionrings.setText("0");
        jtxtchickensalad.setText("0");
        jtxtfishsandwich.setText("0");
        jtxtchickensandwich.setText("0");
        jtxtcheesesandwich.setText("0");
        jtxthashbrown.setText("0");
       jtxttoastedbagel.setText("0");
       jtxtpineapplestick.setText("0");
       jtxtchocolatemuffin.setText("0");
       jtxtpancakessyrup.setText("0");
       jtxtpaymentmethod.setText("0");
       jtxttea.setText("0");
       jtxtcola.setText("0");
       jtxtcoffee.setText("0");
       jtxtorange.setText("0");
       jtxtbottlewater.setText("0");
       jtxtvanilacone.setText("0");
       jtxtvanilashake.setText("0");
       jtxtstrawberryshake.setText("0");
       jtxtchocolatemilkshake.setText("0");
       jtxtchange.setText(null);
       jtxtsubtotal.setText(null);
       jtxttax.setText(null);
       jtxttotal.setText(null);
       //===================
       
       // all the textfield
       
       /*jtxtfries.setEnabled(false);
       jtxtsalad.setEnabled(false);
       jtxthamburger.setEnabled(false);
       jtxtonionrings.setEnabled(false);
       jtxtchickensalad.setEnabled(false);
       jtxtfishsandwich.setEnabled(false);
       jtxtcheesesandwich.setEnabled(false);
       jtxtchickensandwich.setEnabled(false);
       jtxthashbrown.setEnabled(false);
       jtxttoastedbagel.setEnabled(false);
       jtxtpineapplestick.setEnabled(false);
       jtxtchocolatemuffin.setEnabled(false);
       jtxtpancakessyrup.setEnabled(false);
       jtxttea.setEnabled(false);
       jtxtcoffee.setEnabled(false);
       jtxtcola.setEnabled(false);
       jtxtorange.setEnabled(false);
       jtxtbottlewater.setEnabled(false);
       jtxtvanilacone.setEnabled(false);
       jtxtvanilashake.setEnabled(false);
       jtxtstrawberryshake.setEnabled(false);
       jtxtchocolatemilkshake.setEnabled(false);*/
       
       
       
       
       //===================
       //checkbox field
       jchkfries.setSelected(false);
       jchksalad.setSelected(false);
       jchkchickensalad.setSelected(false);
       jchkhamburger.setSelected(false);
       jchkonionrings.setSelected(false);
       jchkfishsandwich.setSelected(false);
       jchkcheesesandwich.setSelected(false);
       jchkchickensandwich.setSelected(false);
       jchkhashbrown.setSelected(false);
       jchktoastedbagel.setSelected(false);
       jchkpineapplestick.setSelected(false);
       jchkchocolatemuffin.setSelected(false);
       jchkpancakessyrup.setSelected(false);
       jchktea.setSelected(false);
       jchkcola.setSelected(false);
       jchkcoffee.setSelected(false);
       jchkorange.setSelected(false);
       jchkbottlewater.setSelected(false);
       jchkvanilacone.setSelected(false);
       jchkvanilashake.setSelected(false);
       jchkstrawberryshake.setSelected(false);
       jchkchocolatemilkshake.setSelected(false);
       
       
       
       
       
      
       

       
       
        
    }//GEN-LAST:event_jbuttonresetActionPerformed
//always allow a numeric number in this field
    private void jtxtfriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfriesKeyTyped
       char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }
    }//GEN-LAST:event_jtxtfriesKeyTyped
//always allow a numeric number in this field
    private void jtxtsaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsaladKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsaladKeyTyped
//always allow a numeric number in this field
    private void jtxthamburgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxthamburgerKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jtxthamburgerKeyTyped
//always allow a numeric number in this field
    private void jtxtonionringsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtonionringsKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtonionringsKeyTyped
//always allow a numeric number in this field
    private void jtxtchickensaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchickensaladKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }       
    }//GEN-LAST:event_jtxtchickensaladKeyTyped
//always allow a numeric number in this field
    private void jtxtfishsandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfishsandwichKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtfishsandwichKeyTyped
//always allow a numeric number in this field
    private void jtxtcheesesandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcheesesandwichKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtcheesesandwichKeyTyped
//always allow a numeric number in this field
    private void jtxtchickensandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchickensandwichKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtchickensandwichKeyTyped
//always allow a numeric number in this field
    private void jtxtpaymentmethodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpaymentmethodKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtpaymentmethodKeyTyped
//always allow a numeric number in this field
    private void jtxthashbrownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxthashbrownKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxthashbrownKeyTyped
//always allow a numeric number in this field
    private void jtxttoastedbagelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttoastedbagelKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxttoastedbagelKeyTyped
//always allow a numeric number in this field
    private void jtxtpineapplestickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpineapplestickKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtpineapplestickKeyTyped
//always allow a numeric number in this field
    private void jtxtchocolatemuffinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchocolatemuffinKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtchocolatemuffinKeyTyped
//always allow a numeric number in this field
    private void jtxtpancakessyrupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpancakessyrupKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }       
    }//GEN-LAST:event_jtxtpancakessyrupKeyTyped
//always allow a numeric number in this field
    private void jtxtchangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchangeKeyTyped
       
    }//GEN-LAST:event_jtxtchangeKeyTyped
//always allow a numeric number in this field
    private void jtxtteaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtteaKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtteaKeyTyped
//always allow a numeric number in this field
    private void jtxtcolaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcolaKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtcolaKeyTyped
//always allow a numeric number in this field
    private void jtxtcoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcoffeeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtcoffeeKeyTyped
//always allow a numeric number in this field
    private void jtxtorangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtorangeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtorangeKeyTyped
//always allow a numeric number in this field
    private void jtxtbottlewaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbottlewaterKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }       
    }//GEN-LAST:event_jtxtbottlewaterKeyTyped
//always allow a numeric number in this field
    private void jtxtvanilaconeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvanilaconeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }      
    }//GEN-LAST:event_jtxtvanilaconeKeyTyped
//always allow a numeric number in this field
    private void jtxtvanilashakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvanilashakeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtvanilashakeKeyTyped
//always allow a numeric number in this field
    private void jtxtstrawberryshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtstrawberryshakeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtstrawberryshakeKeyTyped
//always allow a numeric number in this field
    private void jtxtchocolatemilkshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchocolatemilkshakeKeyTyped
 char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber==KeyEvent.VK_BACK_SPACE)||(iNumber==KeyEvent.VK_DELETE))
          {
    evt.consume();
    }        
    }//GEN-LAST:event_jtxtchocolatemilkshakeKeyTyped

    private void jtxtchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtchangeActionPerformed
     
    }//GEN-LAST:event_jtxtchangeActionPerformed
//enable check box when clicked
    private void jchkfriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkfriesActionPerformed
        if(jchkfries.isSelected())
        {
            jtxtfries.setEditable(true);
            jtxtfries.requestFocus();
            jtxtfries.setText("");
        }
        else{
        jtxtfries.setEditable(false);
        jtxtfries.setText("0");
        }
    }//GEN-LAST:event_jchkfriesActionPerformed
//enable check box when clicked
    private void jchksaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchksaladActionPerformed
if(jchksalad.isSelected())
        {
            jtxtsalad.setEditable(true);
            jtxtsalad.requestFocus();
            jtxtsalad.setText("");
        }
        else{
        jtxtsalad.setEditable(false);
        jtxtsalad.setText("0");
        }        
    }//GEN-LAST:event_jchksaladActionPerformed
//enable check box when clicked
    private void jchkhamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkhamburgerActionPerformed
if(jchkhamburger.isSelected())
        {
            jtxthamburger.setEditable(true);
            jtxthamburger.requestFocus();
            jtxthamburger.setText("");
        }
        else{
        jtxthamburger.setEditable(false);
        jtxthamburger.setText("0");
        }          
    }//GEN-LAST:event_jchkhamburgerActionPerformed
//enable check box when clicked
    private void jchkonionringsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkonionringsActionPerformed
if(jchkonionrings.isSelected())
        {
            jtxtonionrings.setEditable(true);
            jtxtonionrings.requestFocus();
             jtxtonionrings.setText("");
        }
        else{
        jtxtonionrings.setEditable(false);
         jtxtonionrings.setText("0");
        }         
    }//GEN-LAST:event_jchkonionringsActionPerformed
//enable check box when clicked
    private void jchkchickensaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkchickensaladActionPerformed
if(jchkchickensalad.isSelected())
        {
            jtxtchickensalad.setEditable(true);
            jtxtchickensalad.requestFocus();
            jtxtchickensalad.setText("");
        }
        else{
        jtxtchickensalad.setEditable(false);
        jtxtchickensalad.setText("0");
        }        
    }//GEN-LAST:event_jchkchickensaladActionPerformed
//enable check box when clicked
    private void jchkfishsandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkfishsandwichActionPerformed
if(jchkfishsandwich.isSelected())
        {
            jtxtfishsandwich.setEditable(true);
            jtxtfishsandwich.requestFocus();
            jtxtfishsandwich.setText("");
        }
        else{
        jtxtfishsandwich.setEditable(false);
        jtxtfishsandwich.setText("0");
        }      
    }//GEN-LAST:event_jchkfishsandwichActionPerformed
//enable check box when clicked
    private void jchkcheesesandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcheesesandwichActionPerformed
if(jchkcheesesandwich.isSelected())
        {
            jtxtcheesesandwich.setEditable(true);
            jtxtcheesesandwich.requestFocus();
            jtxtcheesesandwich.setText("");
        }
        else{
        jtxtcheesesandwich.setEditable(false);
        jtxtcheesesandwich.setText("0");
        }        
    }//GEN-LAST:event_jchkcheesesandwichActionPerformed
//enable check box when clicked
    private void jchktoastedbagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchktoastedbagelActionPerformed
if(jchktoastedbagel.isSelected())
        {
            jtxttoastedbagel.setEditable(true);
            jtxttoastedbagel.requestFocus();
            jtxttoastedbagel.setText("");
        }
        else{
        jtxttoastedbagel.setEditable(false);
        jtxttoastedbagel.setText("0");
        }         
    }//GEN-LAST:event_jchktoastedbagelActionPerformed
//enable check box when clicked
    private void jchkpineapplestickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkpineapplestickActionPerformed
if(jchkpineapplestick.isSelected())
        {
            jtxtpineapplestick.setEditable(true);
            jtxtpineapplestick.requestFocus();
            jtxtpineapplestick.setText("");
        }
        else{
        jtxtpineapplestick.setEditable(false);
        jtxtpineapplestick.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jchkpineapplestickActionPerformed
//enable check box when clicked
    private void jchkchocolatemuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkchocolatemuffinActionPerformed
if(jchkchocolatemuffin.isSelected())
        {
            jtxtchocolatemuffin.setEditable(true);
            jtxtchocolatemuffin.requestFocus();
            jtxtchocolatemuffin.setText("");
        }
        else{
        jtxtchocolatemuffin.setEditable(false);
        jtxtchocolatemuffin.setText("0");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jchkchocolatemuffinActionPerformed
//enable check box when clicked
    private void jchkpancakessyrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkpancakessyrupActionPerformed
if(jchkpancakessyrup.isSelected())
        {
            jtxtpancakessyrup.setEditable(true);
            jtxtpancakessyrup.requestFocus();
            jtxtpancakessyrup.setText("");
        }
        else{
        jtxtpancakessyrup.setEditable(false);
        jtxtpancakessyrup.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jchkpancakessyrupActionPerformed
//enable check box when clicked
    private void jchkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkteaActionPerformed
if(jchktea.isSelected())
        {
            jtxttea.setEditable(true);
            jtxttea.requestFocus();
            jtxttea.setText("");
        }
        else{
        jtxttea.setEditable(false);
         jtxttea.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jchkteaActionPerformed
//enable check box when clicked
    private void jchkcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcolaActionPerformed
if(jchkcola.isSelected())
        {
            jtxtcola.setEditable(true);
            jtxtcola.requestFocus();
             jtxtcola.setText("");
        }
        else{
        jtxtcola.setEditable(false);
         jtxtcola.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jchkcolaActionPerformed
//enable check box when clicked
    private void jchkcoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcoffeeActionPerformed
if(jchkcoffee.isSelected())
        {
            jtxtcoffee.setEditable(true);
            jtxtcoffee.requestFocus();
             jtxtcoffee.setText("");
        }
        else{
        jtxtcoffee.setEditable(false);
         jtxtcoffee.setText("0");
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jchkcoffeeActionPerformed
//enable check box when clicked
    private void jchkorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkorangeActionPerformed
if(jchkorange.isSelected())
        {
            jtxtorange.setEditable(true);
            jtxtorange.requestFocus();
             jtxtorange.setText("");
        }
        else{
        jtxtorange.setEditable(false);
         jtxtorange.setText("0");
        }         
    }//GEN-LAST:event_jchkorangeActionPerformed
//enable check box when clicked
    private void jchkbottlewaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbottlewaterActionPerformed
if(jchkbottlewater.isSelected())
        {
            jtxtbottlewater.setEditable(true);
            jtxtbottlewater.requestFocus();
             jtxtbottlewater.setText("");
        }
        else{
        jtxtbottlewater.setEditable(false);
         jtxtbottlewater.setText("0");
        }        
    }//GEN-LAST:event_jchkbottlewaterActionPerformed
//enable check box when clicked
    private void jchkvanilaconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkvanilaconeActionPerformed
if(jchkvanilacone.isSelected())
        {
            jtxtvanilacone.setEditable(true);
            jtxtvanilacone.requestFocus();
             jtxtvanilacone.setText("");
        }
        else{
        jtxtvanilacone.setEditable(false);
         jtxtvanilacone.setText("0");
        }         
    }//GEN-LAST:event_jchkvanilaconeActionPerformed
//enable check box when clicked
    private void jchkvanilashakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkvanilashakeActionPerformed
if(jchkvanilashake.isSelected())
        {
            jtxtvanilashake.setEditable(true);
            jtxtvanilashake.requestFocus();
             jtxtvanilashake.setText("");
        }
        else{
        jtxtvanilashake.setEditable(false);
         jtxtvanilashake.setText("0");
        }         
    }//GEN-LAST:event_jchkvanilashakeActionPerformed
//enable check box when clicked
    private void jchkstrawberryshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkstrawberryshakeActionPerformed
if(jchkstrawberryshake.isSelected())
        {
            jtxtstrawberryshake.setEditable(true);
            jtxtstrawberryshake.requestFocus();
             jtxtstrawberryshake.setText("");
        }
        else{
        jtxtstrawberryshake.setEditable(false);
         jtxtstrawberryshake.setText("0");
        }        
    }//GEN-LAST:event_jchkstrawberryshakeActionPerformed
//enable check box when clicked
    private void jchkchocolatemilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkchocolatemilkshakeActionPerformed
if(jchkchocolatemilkshake.isSelected())
        {
            jtxtchocolatemilkshake.setEditable(true);
            jtxtchocolatemilkshake.requestFocus();
             jtxtchocolatemilkshake.setText("");
        }
        else{
        jtxtchocolatemilkshake.setEditable(false);
         jtxtchocolatemilkshake.setText("0");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jchkchocolatemilkshakeActionPerformed

    //inhertence part 
     class fastfood{
         double price;
         public void addition(double x, double y){
             System.out.println(x+y);
         }
          public void subtraction(double x, double y){
             System.out.println(x-y);//x is given money and y is totall amount
         }
          public class meal extends fastfood{
              public void total(double x,double y){
                  System.out.println(x);
              }
                      
          }
           public class  sandwich extends fastfood{
              public void total(double x,double y){
                  System.out.println(x);
              }
                      
          }
            public class desserts extends fastfood{
              public void total(double x,double y){
                  System.out.println(x);
              }
                      
          }
             public class drink extends fastfood{
              public void total(double x,double y){
                  System.out.println(x);
              }
                      
          }
              public class shake extends fastfood{
              public void total(double x,double y){
                  System.out.println(x);
              }
                      
          }
         
     }
    private void jtxtpaymentmethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpaymentmethodActionPerformed
        
    }//GEN-LAST:event_jtxtpaymentmethodActionPerformed
//work of the toal button
    private void jbuttontotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttontotalActionPerformed
        itemcost[0]=Double.parseDouble(jtxtfries.getText());
        
        itemcost[1]=Double.parseDouble(jtxtsalad.getText());
        itemcost[2]=Double.parseDouble(jtxthamburger.getText());
        itemcost[3]=Double.parseDouble(jtxtonionrings.getText());
        itemcost[4]=Double.parseDouble(jtxtchickensalad.getText());
        itemcost[5]=Double.parseDouble(jtxtfishsandwich.getText());
        itemcost[6]=Double.parseDouble(jtxtcheesesandwich.getText());
        itemcost[7]=Double.parseDouble(jtxtchickensandwich.getText());
        itemcost[8]=Double.parseDouble(jtxthashbrown.getText());
        itemcost[9]=Double.parseDouble(jtxttoastedbagel.getText()); 
        itemcost[10]=Double.parseDouble(jtxtpineapplestick.getText());
        itemcost[11]=Double.parseDouble(jtxtchocolatemuffin.getText());
        itemcost[12]=Double.parseDouble(jtxtpancakessyrup.getText());
        itemcost[13]=Double.parseDouble(jtxttea.getText());
        itemcost[14]=Double.parseDouble(jtxtcola.getText()); 
        itemcost[15]=Double.parseDouble(jtxtcoffee.getText());
        itemcost[16]=Double.parseDouble(jtxtorange.getText());
        itemcost[17]=Double.parseDouble(jtxtbottlewater.getText()); 
        itemcost[18]=Double.parseDouble(jtxtvanilacone.getText());
        itemcost[19]=Double.parseDouble(jtxtvanilashake.getText());
        itemcost[20]=Double.parseDouble(jtxtstrawberryshake.getText());
        itemcost[21]=Double.parseDouble(jtxtchocolatemilkshake.getText());
        iChange=Double.parseDouble(jtxtpaymentmethod.getText());
        
        
        String PaymentMethod= (String)jcombopaymentmethod.getSelectedItem();
        
        if(PaymentMethod=="Cash")
        { 
        iSubTotal=(itemcost[0]*price_fries)+(itemcost[1]*price_salad)+(itemcost[2]*price_hamburger)+(itemcost[3]*price_onionrings)+(itemcost[4]*price_chickensalad)+
                (itemcost[5]*price_fishsandwich)+(itemcost[6]*price_cheesesandwich)+(itemcost[7]*price_chickensandwich)+
                (itemcost[8]*price_hashbrown)+(itemcost[9]*price_toastedbagel)+(itemcost[10]*price_pineapplestick)+(itemcost[11]*price_chocolatemuffin)
                +(itemcost[12]*price_pancakesyrup)+(itemcost[13]*price_tea)+(itemcost[14]*price_cola)+(itemcost[15]*price_coffee)+(itemcost[16]*price_orange)+
               (itemcost[17]*price_bottlewater)+(itemcost[18]*price_vanilacone)+(itemcost[19]*price_vanilashake)+(itemcost[20]*price_strawberryshake)
                +(itemcost[21]*price_chocolatemilkshake);
        
        if(iChange>=iSubTotal)
        {
        iTax=(iSubTotal*taxrate)/100;
        String cTax=String.format("RM %.2f",iTax);
        jtxttax.setText(cTax);
        
         String cSubTotal=String.format("RM %.2f",iSubTotal);
        jtxtsubtotal.setText(cSubTotal);
        
        
        String cTotal= String.format("RM %.2f",iSubTotal+iTax);
        jtxttotal.setText(cTotal);
        
       String cChange=String.format("RM %.2f",iChange-(iSubTotal+iTax));
       jtxtchange.setText(cChange);
       
        }
        else{
 
            JOptionPane.showMessageDialog(null,"Not enough Cash enterd.", "Fast Food", JOptionPane.OK_OPTION);
        }
        }
        else if(PaymentMethod=="Debit card"||PaymentMethod=="Master Card"||PaymentMethod=="Visa Card")
        {
           //calcultae everything 
        iSubTotal=(itemcost[0]*price_fries)+(itemcost[1]*price_salad)+(itemcost[2]*price_hamburger)+(itemcost[3]*price_onionrings)+(itemcost[4]*price_chickensalad)+
                (itemcost[5]*price_fishsandwich)+(itemcost[6]*price_cheesesandwich)+(itemcost[7]*price_chickensandwich)+
                (itemcost[8]*price_hashbrown)+(itemcost[9]*price_toastedbagel)+(itemcost[10]*price_pineapplestick)+(itemcost[11]*price_chocolatemuffin)
                +(itemcost[12]*price_pancakesyrup)+(itemcost[13]*price_tea)+(itemcost[14]*price_cola)+(itemcost[15]*price_coffee)+(itemcost[16]*price_orange)+
               (itemcost[17]*price_bottlewater)+(itemcost[18]*price_vanilacone)+(itemcost[19]*price_vanilashake)+(itemcost[20]*price_strawberryshake)
                +(itemcost[21]*price_chocolatemilkshake);
        
        //calculate the tax
        iTax=(iSubTotal*taxrate)/100;
        String cTax=String.format("RM %.2f",iTax);
        jtxttax.setText(cTax);
        //calculate and print subtotal
         String cSubTotal=String.format("RM %.2f",iSubTotal);
        jtxtsubtotal.setText(cSubTotal);
        
        
        String cTotal= String.format("RM %.2f",iSubTotal+iTax);
        jtxttotal.setText(cTotal);
        }
        
        
    }//GEN-LAST:event_jbuttontotalActionPerformed
//overloading usi9ng same  method
    class FastFoodmenu{
        private void displaypayment(int payment){
            System.out.println(payment);
        }
        private void displaypayment(double payment)
        {
            System.out.println(payment); 
        }
        public void displaychange(int change){
            System.out.println(change);
        } 
        public void displaychange(double change){
            System.out.println(change);
        }
        public void displayisubtotal(int isubtotal){
                System.out.println(isubtotal);
    }
    
    }
    private void jcombopaymentmethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombopaymentmethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombopaymentmethodActionPerformed

    private void jtxtfriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfriesActionPerformed

    private void jtxtcoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcoffeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbuttonexit;
    private javax.swing.JButton jbuttonreset;
    private javax.swing.JButton jbuttontotal;
    private javax.swing.JCheckBox jchkbottlewater;
    private javax.swing.JCheckBox jchkcheesesandwich;
    private javax.swing.JCheckBox jchkchickensalad;
    private javax.swing.JCheckBox jchkchickensandwich;
    private javax.swing.JCheckBox jchkchocolatemilkshake;
    private javax.swing.JCheckBox jchkchocolatemuffin;
    private javax.swing.JCheckBox jchkcoffee;
    private javax.swing.JCheckBox jchkcola;
    private javax.swing.JCheckBox jchkfishsandwich;
    private javax.swing.JCheckBox jchkfries;
    private javax.swing.JCheckBox jchkhamburger;
    private javax.swing.JCheckBox jchkhashbrown;
    private javax.swing.JCheckBox jchkonionrings;
    private javax.swing.JCheckBox jchkorange;
    private javax.swing.JCheckBox jchkpancakessyrup;
    private javax.swing.JCheckBox jchkpineapplestick;
    private javax.swing.JCheckBox jchksalad;
    private javax.swing.JCheckBox jchkstrawberryshake;
    private javax.swing.JCheckBox jchktea;
    private javax.swing.JCheckBox jchktoastedbagel;
    private javax.swing.JCheckBox jchkvanilacone;
    private javax.swing.JCheckBox jchkvanilashake;
    private javax.swing.JComboBox<String> jcombopaymentmethod;
    private javax.swing.JLabel jlbfastfoodandvegetarian;
    private javax.swing.JLabel jlblchange;
    private javax.swing.JLabel jlbldesserts;
    private javax.swing.JLabel jlbldrinks;
    private javax.swing.JLabel jlblpaymentmethod;
    private javax.swing.JLabel jlblsandwich;
    private javax.swing.JLabel jlblshakes;
    private javax.swing.JLabel jlblsubtotal;
    private javax.swing.JLabel jlbltax;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JLabel jlbluppername;
    private javax.swing.JTextField jtxtbottlewater;
    private javax.swing.JTextField jtxtchange;
    private javax.swing.JTextField jtxtcheesesandwich;
    private javax.swing.JTextField jtxtchickensalad;
    private javax.swing.JTextField jtxtchickensandwich;
    private javax.swing.JTextField jtxtchocolatemilkshake;
    private javax.swing.JTextField jtxtchocolatemuffin;
    private javax.swing.JTextField jtxtcoffee;
    private javax.swing.JTextField jtxtcola;
    private javax.swing.JTextField jtxtfishsandwich;
    private javax.swing.JTextField jtxtfries;
    private javax.swing.JTextField jtxthamburger;
    private javax.swing.JTextField jtxthashbrown;
    private javax.swing.JTextField jtxtonionrings;
    private javax.swing.JTextField jtxtorange;
    private javax.swing.JTextField jtxtpancakessyrup;
    private javax.swing.JTextField jtxtpaymentmethod;
    private javax.swing.JTextField jtxtpineapplestick;
    private javax.swing.JTextField jtxtsalad;
    private javax.swing.JTextField jtxtstrawberryshake;
    private javax.swing.JTextField jtxtsubtotal;
    private javax.swing.JTextField jtxttax;
    private javax.swing.JTextField jtxttea;
    private javax.swing.JTextField jtxttoastedbagel;
    private javax.swing.JTextField jtxttotal;
    private javax.swing.JTextField jtxtvanilacone;
    private javax.swing.JTextField jtxtvanilashake;
    // End of variables declaration//GEN-END:variables
}
